### ISSUE TITLE
Version on DockerHub is out of date

### ISSUE THREAD

**Issue by fastloris** [xebialabs-community/xl-docker-demo-xlr#8]
The instructions here say you can pull this image at xebialabs/xl-docker-demo-xlr:latest, but it has not been updated since 8.0 came out.

**Comment by amitmohleji** [comment]
fixed. I'll have to check with @jdewinne why it didn't kickoff the build for latest by itself

**Comment by jdewinne** [comment]
Hmmm. It might have to do with Docker Hub only looking at changes to the docker file. I would expect this to be fixed if we move it to Docker Cloud.
